image:
  repository: ghcr.io/itchyitchy123/stepanel
  tag: v0.2.0
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 8080
resources:
  requests: {cpu: 100m, memory: 128Mi}
  limits: {cpu: 500m, memory: 512Mi}
persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
  accessModes: [ReadWriteOnce]
secrets:
  existingSecret: stepanel-secrets
ingress:
  enabled: false
  className: ""
  host: stepanel.example.com
  annotations: {}
  tls: []
