package main

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

var gitRefPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._/@+-]{0,127}$`)
var gitCommitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)

type gitDeployRequest struct {
	Site       string `json:"site"`
	Repository string `json:"repository"`
	Ref        string `json:"ref"`
}

// gitRepository is deliberately narrower than Git's general URL syntax.  HTTPS
// remains available for public sources; SSH is available only as git@host:path
// and only after a per-site deploy key has been generated by the privileged
// helper.  Personal tokens, passwords, query strings, and arbitrary SSH users
// are never accepted.
type gitRepository struct {
	URL     string
	Host    string
	Private bool
}

var gitSSHRepositoryPattern = regexp.MustCompile(`^git@([A-Za-z0-9.-]+):([A-Za-z0-9._/-]+\.git)$`)

func parseGitRepository(raw, allowedHosts string) (gitRepository, error) {
	raw = strings.TrimSpace(raw)
	if match := gitSSHRepositoryPattern.FindStringSubmatch(raw); match != nil {
		if !gitHostAllowed(allowedHosts, strings.ToLower(match[1])) {
			return gitRepository{}, errors.New("repository host is not in STEPANEL_GIT_ALLOWED_HOSTS")
		}
		return gitRepository{URL: raw, Host: strings.ToLower(match[1]), Private: true}, nil
	}
	repository, err := url.Parse(raw)
	if err != nil || repository.Scheme != "https" || repository.User != nil || repository.Host == "" || repository.Port() != "" || repository.RawQuery != "" || repository.Fragment != "" || strings.ContainsAny(raw, "\x00\r\n") || !strings.HasSuffix(strings.ToLower(repository.Path), ".git") {
		return gitRepository{}, errors.New("repository must be an HTTPS .git URL without credentials or an SSH git@host:path.git URL")
	}
	if !gitHostAllowed(allowedHosts, repository.Hostname()) {
		return gitRepository{}, errors.New("repository host is not in STEPANEL_GIT_ALLOWED_HOSTS")
	}
	return gitRepository{URL: raw, Host: strings.ToLower(repository.Hostname())}, nil
}

type gitDeployResult struct {
	Site       string `json:"site"`
	Repository string `json:"repository"`
	Ref        string `json:"ref"`
	Commit     string `json:"commit"`
	Previous   string `json:"previous_release,omitempty"`
}

type gitRollbackRequest struct {
	Site    string `json:"site"`
	Confirm string `json:"confirm"`
}

type gitWebhookContextKey struct{}

func (a *App) gitWebhook(w http.ResponseWriter, r *http.Request) {
	if a.Config.GitWebhookSecret == "" {
		http.Error(w, "Git webhooks are not configured", http.StatusNotFound)
		return
	}
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 16<<10))
	if err != nil {
		http.Error(w, "invalid webhook body", 400)
		return
	}
	signature := strings.TrimSpace(strings.TrimPrefix(r.Header.Get("X-StePanel-Signature"), "sha256="))
	provided, err := hex.DecodeString(signature)
	digest := hmac.New(sha256.New, []byte(a.Config.GitWebhookSecret))
	_, _ = digest.Write(body)
	if err != nil || !hmac.Equal(provided, digest.Sum(nil)) {
		http.Error(w, "invalid webhook signature", 401)
		return
	}
	request := r.Clone(context.WithValue(r.Context(), gitWebhookContextKey{}, true))
	request.Body = io.NopCloser(bytes.NewReader(body))
	a.gitDeploy(w, request)
}

// gitDeploy intentionally does not evaluate repository-provided build scripts.
// Build execution belongs in a separately sandboxed runner.
func (a *App) gitDeploy(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost || (!a.Auth.CSRF(r) && r.Context().Value(gitWebhookContextKey{}) != true) {
		http.Error(w, "invalid request", http.StatusForbidden)
		return
	}
	var input gitDeployRequest
	if err := decodeJSON(w, r, 16<<10, &input); err != nil {
		http.Error(w, "invalid JSON", http.StatusBadRequest)
		return
	}
	input.Site = safeUser(input.Site)
	input.Repository = strings.TrimSpace(input.Repository)
	input.Ref = strings.TrimSpace(input.Ref)
	if input.Ref == "" {
		input.Ref = "main"
	}
	if input.Site == "" || !gitRefPattern.MatchString(input.Ref) {
		http.Error(w, "invalid site or Git ref", http.StatusUnprocessableEntity)
		return
	}
	repository, err := parseGitRepository(input.Repository, a.Config.GitAllowedHosts)
	if err != nil {
		http.Error(w, err.Error(), http.StatusUnprocessableEntity)
		return
	}
	publicRoot := filepath.Join(a.Config.WebRoot, "sites", input.Site, "public")
	if err := ensureInside(a.Config.WebRoot, publicRoot); err != nil {
		http.Error(w, err.Error(), http.StatusUnprocessableEntity)
		return
	}
	siteRoot := filepath.Dir(publicRoot)
	if info, err := os.Stat(siteRoot); err != nil || !info.IsDir() {
		http.Error(w, "site root does not exist", http.StatusUnprocessableEntity)
		return
	}
	gitPath, err := exec.LookPath("git")
	if err != nil {
		http.Error(w, "Git is not installed", http.StatusServiceUnavailable)
		return
	}
	release := filepath.Join(siteRoot, ".stepanel-release-"+strings.ReplaceAll(newRequestID(), "-", ""))
	if err := os.Mkdir(release, 0700); err != nil {
		http.Error(w, "unable to create release staging directory", http.StatusInternalServerError)
		return
	}
	defer os.RemoveAll(release)
	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Minute)
	defer cancel()
	var cloneOutput []byte
	if repository.Private {
		cloneOutput, err = runBoundedCommand(ctx, helperCommandContext(ctx, a.Config, a.Config.GitCtl, "clone", input.Site, repository.URL, input.Ref, release))
	} else {
		clone := exec.CommandContext(ctx, gitPath, "-c", "credential.helper=", "clone", "--depth", "1", "--branch", input.Ref, "--single-branch", "--no-tags", repository.URL, release)
		clone.Env = append(os.Environ(), "GIT_TERMINAL_PROMPT=0", "GIT_ASKPASS=/bin/false", "GIT_CONFIG_NOSYSTEM=1", "GIT_CONFIG_GLOBAL=/dev/null")
		cloneOutput, err = runBoundedCommand(ctx, clone)
	}
	if err != nil {
		http.Error(w, "Git checkout failed: "+strings.TrimSpace(string(cloneOutput)), http.StatusBadGateway)
		return
	}
	commitOutput, err := runBoundedCommand(ctx, exec.CommandContext(ctx, gitPath, "-C", release, "rev-parse", "HEAD"))
	if err != nil {
		http.Error(w, "unable to identify checked-out commit", http.StatusBadGateway)
		return
	}
	commit := strings.TrimSpace(string(commitOutput))
	if !gitCommitPattern.MatchString(commit) {
		http.Error(w, "Git returned an invalid commit identifier", http.StatusBadGateway)
		return
	}
	if err := validateGitRelease(release, a.Config.MaxEntries); err != nil {
		http.Error(w, "repository contains an unsafe release tree: "+err.Error(), http.StatusUnprocessableEntity)
		return
	}
	if err := os.RemoveAll(filepath.Join(release, ".git")); err != nil {
		http.Error(w, "unable to remove Git metadata from release", http.StatusInternalServerError)
		return
	}
	a.gitActivationMu.Lock()
	defer a.gitActivationMu.Unlock()
	previous := ""
	if _, err := os.Stat(publicRoot); err == nil {
		previous = filepath.Join(siteRoot, ".stepanel-previous-"+strings.ReplaceAll(newRequestID(), "-", ""))
		if err := os.Rename(publicRoot, previous); err != nil {
			http.Error(w, "unable to preserve the current release", http.StatusInternalServerError)
			return
		}
	}
	if err := os.Rename(release, publicRoot); err != nil {
		if previous != "" {
			if rollbackErr := os.Rename(previous, publicRoot); rollbackErr != nil {
				http.Error(w, "unable to activate the new release; rollback failed: "+rollbackErr.Error(), http.StatusServiceUnavailable)
				return
			}
		}
		http.Error(w, "unable to activate the new release", http.StatusInternalServerError)
		return
	}
	if err := siteHelper(a.Config, "seal", input.Site); err != nil {
		if rollbackErr := rollbackGitActivation(publicRoot, previous); rollbackErr != nil {
			http.Error(w, "site isolation failed and release rollback failed: "+rollbackErr.Error(), http.StatusServiceUnavailable)
			return
		}
		http.Error(w, "site isolation could not be restored", http.StatusServiceUnavailable)
		return
	}
	result := gitDeployResult{Site: input.Site, Repository: input.Repository, Ref: input.Ref, Commit: commit, Previous: previous}
	if err := AuditAs(a.Config.AuditLog, a.Auth.Username, "site.git-deployed", input.Site, input.Repository+"@"+commit); err != nil {
		log.Printf("Git release activated but audit persistence is unavailable: %v", err)
	}
	writeJSON(w, http.StatusAccepted, result)
}

func rollbackGitActivation(publicRoot, previous string) error {
	if err := os.RemoveAll(publicRoot); err != nil {
		return fmt.Errorf("remove failed release: %w", err)
	}
	if previous != "" {
		if err := os.Rename(previous, publicRoot); err != nil {
			return fmt.Errorf("restore previous release: %w", err)
		}
	}
	return nil
}

func (a *App) gitRollback(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost || !a.Auth.CSRF(r) {
		http.Error(w, "invalid request", http.StatusForbidden)
		return
	}
	var input gitRollbackRequest
	if err := decodeJSON(w, r, 4096, &input); err != nil {
		http.Error(w, "invalid JSON", http.StatusBadRequest)
		return
	}
	input.Site = safeUser(input.Site)
	if input.Site == "" || input.Confirm != "ROLLBACK "+input.Site {
		http.Error(w, "confirmation must exactly match ROLLBACK <site>", http.StatusUnprocessableEntity)
		return
	}
	siteRoot := filepath.Join(a.Config.WebRoot, "sites", input.Site)
	publicRoot := filepath.Join(siteRoot, "public")
	if err := ensureInside(a.Config.WebRoot, publicRoot); err != nil {
		http.Error(w, "invalid site root", http.StatusUnprocessableEntity)
		return
	}
	a.gitActivationMu.Lock()
	defer a.gitActivationMu.Unlock()
	previous, err := latestPreviousRelease(siteRoot)
	if err != nil {
		http.Error(w, "no previous Git release is available", http.StatusConflict)
		return
	}
	if err := validateGitRelease(previous, a.Config.MaxEntries); err != nil {
		http.Error(w, "previous release failed safety validation", http.StatusConflict)
		return
	}
	if info, err := os.Stat(publicRoot); err != nil || !info.IsDir() {
		http.Error(w, "active site release is unavailable", http.StatusConflict)
		return
	}
	replaced := filepath.Join(siteRoot, ".stepanel-previous-"+strings.ReplaceAll(newRequestID(), "-", ""))
	if err := os.Rename(publicRoot, replaced); err != nil {
		http.Error(w, "unable to preserve the active release", http.StatusInternalServerError)
		return
	}
	if err := os.Rename(previous, publicRoot); err != nil {
		_ = os.Rename(replaced, publicRoot)
		http.Error(w, "unable to activate the previous release", http.StatusInternalServerError)
		return
	}
	if err := siteHelper(a.Config, "seal", input.Site); err != nil {
		_ = os.Rename(publicRoot, previous)
		_ = os.Rename(replaced, publicRoot)
		http.Error(w, "rollback could not restore site isolation", http.StatusServiceUnavailable)
		return
	}
	if err := AuditAs(a.Config.AuditLog, a.Auth.Username, "site.git-rolled-back", input.Site, filepath.Base(previous)); err != nil {
		log.Printf("Git rollback completed but audit persistence is unavailable: %v", err)
	}
	writeJSON(w, http.StatusOK, map[string]string{"site": input.Site, "activated": filepath.Base(previous), "replaced_release": filepath.Base(replaced)})
}

func latestPreviousRelease(siteRoot string) (string, error) {
	entries, err := os.ReadDir(siteRoot)
	if err != nil {
		return "", err
	}
	type candidate struct {
		path string
		time time.Time
	}
	var latest candidate
	for _, entry := range entries {
		if !entry.IsDir() || entry.Type()&os.ModeSymlink != 0 || !strings.HasPrefix(entry.Name(), ".stepanel-previous-") {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		if latest.path == "" || info.ModTime().After(latest.time) || info.ModTime().Equal(latest.time) && entry.Name() > filepath.Base(latest.path) {
			latest = candidate{path: filepath.Join(siteRoot, entry.Name()), time: info.ModTime()}
		}
	}
	if latest.path == "" {
		return "", errors.New("no previous release")
	}
	return latest.path, nil
}

func validateGitAllowedHosts(value string) error {
	if strings.TrimSpace(value) == "" {
		return errors.New("STEPANEL_GIT_ALLOWED_HOSTS must contain at least one hostname")
	}
	for _, host := range strings.Split(value, ",") {
		host = strings.TrimSpace(strings.ToLower(host))
		if host == "" || strings.ContainsAny(host, "\x00\r\n:/") || net.ParseIP(host) != nil || !domainPattern.MatchString(host) {
			return fmt.Errorf("STEPANEL_GIT_ALLOWED_HOSTS contains invalid hostname %q", host)
		}
	}
	return nil
}

func gitHostAllowed(allowed, host string) bool {
	host = strings.ToLower(strings.TrimSuffix(host, "."))
	for _, candidate := range strings.Split(allowed, ",") {
		if host == strings.TrimSpace(strings.ToLower(candidate)) {
			return true
		}
	}
	return false
}

func validateGitRelease(root string, maxEntries int) error {
	if maxEntries < 1 {
		maxEntries = 100000
	}
	entries := 0
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		entries++
		if entries > maxEntries {
			return errors.New("release exceeds the configured entry limit")
		}
		if path == root || strings.HasPrefix(path, filepath.Join(root, ".git")+string(os.PathSeparator)) || path == filepath.Join(root, ".git") {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if entry.Type()&os.ModeSymlink != 0 || !entry.IsDir() && !info.Mode().IsRegular() {
			return fmt.Errorf("%s is not a regular file or directory", filepath.Base(path))
		}
		return nil
	})
}

func newRequestID() string {
	id, err := randomSecret()
	if err != nil {
		return time.Now().UTC().Format("20060102150405.000000000")
	}
	return id
}
