#!/usr/bin/env bash
set -Eeuo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
output=${1:-"$repo_root/docs/lab-results/$(date -u +%F)-recovery-drills.md"}
mkdir -p "$(dirname "$output")"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

patterns=(
  "TestRestoreSQLDropsPartiallyImportedDatabase|TestRestoreFailureRestoresExistingSite"
  "TestRecoverTransactionDatabases|TestRecoverSiteTransactions|TestSiteTransactionRollback"
  "TestGitRollbackAtomicallySwapsPreviousRelease|TestProxyDeleteRestoresConfigWhenReloadFails"
  "TestReconcileWorkersRetainsPendingStateWhenHelperFails|TestReconcilePythonAppsRetainsPendingStateWhenHelperFails|TestReconcilePHPProfilesRetainsPendingStateWhenHelperFails"
)
names=(
  "Partial SQL import cleanup"
  "Interrupted transaction recovery"
  "Configuration rollback"
  "Pending runtime reconciliation"
)

cd "$repo_root"
{
  printf '# Recovery drill results — %s\n\n' "$(date -u +%F)"
  printf 'Generated by `%s` at %s UTC.\n\n' 'deploy/lab/run-recovery-drills.sh' "$(date -u +%FT%TZ)"
  printf 'These are repository-level tests using synthetic temporary data; they are not a substitute for the disposable Docker/systemd lab.\n\n'
  printf '| Scenario | Result | Elapsed |\n| --- | --- | ---: |\n'
} > "$output"

for i in "${!patterns[@]}"; do
  start=$(date +%s)
  if GOCACHE=${GOCACHE:-/tmp/stepanel-go-cache} GOMAXPROCS=${GOMAXPROCS:-1} GOFLAGS="${GOFLAGS:--p=1}" go test -run "${patterns[$i]}" -count=1 ./ >"$tmp" 2>&1; then
    result=PASS
  else
    result=FAIL
  fi
  elapsed=$(( $(date +%s) - start ))
  printf '| %s | **%s** | %ss |\n' "${names[$i]}" "$result" "$elapsed" >> "$output"
  if [[ $result != PASS ]]; then
    cat "$tmp" >&2
    exit 1
  fi
done

cat >> "$output" <<'EOF'

## Scope

Passing results demonstrate the tested rollback and pending-state contracts.
They do not prove power-loss recovery, real systemd behavior, disk exhaustion,
database-server failure, off-site transfer interruption, or target-OS install
compatibility. Run the disposable lab on a host with Docker and systemd
support, retain its logs and readiness/audit evidence, and append those results
separately.
EOF

printf 'Wrote recovery results to %s\n' "$output"
